version: '3'

services:
  api:
    build: ./
    ports:
      - 8002:8000
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db/pokmg
  
  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017 # only for development and debugging
    volumes:
      - pokmg:/data/db

volumes:
  pokmg: