version: '3'

services:
  api:
    build: ./
    ports:
      - 8003:8000
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db/pokly
  
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - pokly:/data/db

volumes:
  pokly: